version: '2'
services:
  sam-postgres-db:
    image: postgres:10.5-alpine
    container_name: sam-postgres-db
    environment:
      - POSTGRES_PASSWORD=3012
    ports:
      - '54321:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
